version: '3.8'

services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtogobackendcontainer
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:8080"
    networks:
      - mtogo-network

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: mtogobackendprometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9097:9090"
    networks:
      - mtogo-network

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: mtogobackendgrafana
    ports:
      - "3007:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - mtogo-network

# Volumes to persist data
volumes:
  sql_data:
  grafana_data:

# Networks to connect the services
networks:
  mtogo-network:
    driver: bridge
